eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://eureka.chenshuang.xyz:8761/eureka/
server:
  port: 8082  #服务端口号
spring:
  application:
    name: eureka-provider #服务名称--调用的时候根据名称来调用该服务的方法